#!/usr/bin/env bash
# Script to connect to server using SSH with private key

# Define server IP address
server_ip="100.26.159.52"

# Specify private key file
private_key="~/.ssh/school"

# Connect to server using SSH
ssh -i "$private_key" ubuntu@"$server_ip"